ALTER TABLE "Bill" ADD COLUMN "loyaltyPointsRedeemed" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Bill" ADD COLUMN "loyaltyDiscount" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Bill" ADD COLUMN "loyaltyDiscountPaise" BIGINT;
