export const QUEUE_NAMES = Object.freeze({
  reminderQueue: "kiranaos-reminders",
  reportsQueue: "kiranaos-reports",
  exportsQueue: "kiranaos-exports",
  backupQueue: "kiranaos-backups",
  syncCleanupQueue: "kiranaos-sync-cleanup",
  webhooksQueue: "kiranaos-webhooks",
  assuranceQueue: "kiranaos-assurance",
});

export const JOB_NAMES = Object.freeze({
  GENERATE_DAILY_CLOSING: "GENERATE_DAILY_CLOSING",
  GENERATE_REPORT_EXPORT: "GENERATE_REPORT_EXPORT",
  GENERATE_CSV_EXPORT: "GENERATE_CSV_EXPORT",
  GENERATE_REPORT_PDF: "GENERATE_REPORT_PDF",
  CLEANUP_EXPIRED_EXPORTS: "CLEANUP_EXPIRED_EXPORTS",
  WORKER_HEALTHCHECK: "WORKER_HEALTHCHECK",
  SEND_WHATSAPP_REMINDER: "SEND_WHATSAPP_REMINDER",
  CLEANUP_SYNC_EVENTS: "CLEANUP_SYNC_EVENTS",
  ARCHIVE_OLD_SYNC_EVENTS: "ARCHIVE_OLD_SYNC_EVENTS",
  RUN_SHOP_BACKUP: "RUN_SHOP_BACKUP",
  RUN_DATABASE_BACKUP: "RUN_DATABASE_BACKUP",
  CLEANUP_EXPIRED_BACKUPS: "CLEANUP_EXPIRED_BACKUPS",
  DELIVER_WEBHOOK: "DELIVER_WEBHOOK",
  RUN_SCHEDULED_ASSURANCE: "RUN_SCHEDULED_ASSURANCE",
  RECOMPUTE_ASSURANCE_BASELINES: "RECOMPUTE_ASSURANCE_BASELINES",
});

export function listQueueNames() {
  return Object.values(QUEUE_NAMES);
}
