export const capabilities = [
  "BASIC_INVENTORY", "PACK_CONVERSION", "BATCH_TRACKING", "EXPIRY_TRACKING",
  "SUPPLIER_RETURNS", "WHOLESALE_PRICING", "SALES_ORDERS", "DELIVERY_ORDERS",
  "BOM", "PRODUCTION_RUNS", "BATCH_GENEALOGY", "PACKAGING_SKUS",
  "QUALITY_CONTROL", "WASTAGE_TRACKING", "WHOLESALE_ORDERS", "EXPORT_DOCUMENTS",
];

export default capabilities;
