import { Router } from "express";
import { requireAuth, requireRole } from "../../middleware/auth.js";
import { requireOwnerPin, requireShop } from "../../middleware/permissions.js";
import { validate, validateQuery } from "../../middleware/validate.js";
import { requireDeviceActivated } from "../../modules/devices/device.middleware.js";
import { requireCapability } from "../../modules/shops/businessProfile.middleware.js";
import { requireLocationAccess } from "../../modules/stores/location-access.service.js";
import { createBomSchema, createRunSchema, completeRunSchema, traceQuerySchema, createTradeOrderSchema, allocateTradeOrderSchema, packTradeOrderSchema, dispatchTradeOrderSchema, attachTradeBillSchema, returnTradeOrderSchema, tradeOrderListQuerySchema } from "./manufacturing.schemas.js";
import * as ctrl from "./manufacturing.controller.js";

const router = Router();
router.use(requireAuth, requireShop, requireDeviceActivated(), requireCapability("PRODUCTION_RUNS"));
router.get("/overview", ctrl.overview);
router.get("/boms", ctrl.boms);
router.post("/boms", requireRole("owner", "admin"), validate(createBomSchema), ctrl.createBom);
router.post("/runs", requireRole("owner", "admin"), requireLocationAccess("inventory"), validate(createRunSchema), ctrl.createRun);
router.post("/runs/:id/complete", requireRole("owner", "admin"), requireLocationAccess("inventory"), validate(completeRunSchema), ctrl.completeRun);
router.post("/runs/:id/release", requireRole("owner", "admin"), requireLocationAccess("inventory"), ctrl.releaseRun);
router.get("/trace", validateQuery(traceQuerySchema), ctrl.trace);
router.get("/trade-orders", validateQuery(tradeOrderListQuerySchema), ctrl.tradeOrders);
router.get("/trade-orders/:id", ctrl.tradeOrder);
router.post("/trade-orders", requireRole("owner", "admin"), requireLocationAccess("inventory"), validate(createTradeOrderSchema), ctrl.createTradeOrder);
router.post("/trade-orders/:id/confirm", requireRole("owner", "admin"), ctrl.confirmTradeOrder);
router.post("/trade-orders/:id/allocate", requireRole("owner", "admin"), requireLocationAccess("inventory"), validate(allocateTradeOrderSchema), ctrl.allocateTradeOrder);
router.post("/trade-orders/:id/auto-allocate", requireRole("owner", "admin"), requireLocationAccess("inventory"), ctrl.autoAllocateTradeOrder);
router.post("/trade-orders/:id/pack", requireRole("owner", "admin"), validate(packTradeOrderSchema), ctrl.packTradeOrder);
router.post("/trade-orders/:id/dispatch", requireRole("owner", "admin"), requireLocationAccess("inventory"), validate(dispatchTradeOrderSchema), ctrl.dispatchTradeOrder);
router.post("/trade-orders/:id/invoice", requireRole("owner", "admin"), validate(attachTradeBillSchema), ctrl.attachTradeBill);
router.post("/trade-orders/:id/cancel", requireRole("owner", "admin"), ctrl.cancelTradeOrder);
router.post("/trade-orders/:id/return", requireRole("owner", "admin"), requireOwnerPin, validate(returnTradeOrderSchema), ctrl.returnTradeOrder);
router.get("/trade-orders/:id/documents", ctrl.tradeDocuments);
router.get("/trade-orders/:id/documents/:kind.pdf", ctrl.tradeDocumentPdf);
export default router;
