"use client";
import { useState } from "react";
const rooms=[
 ["Valley Sanctuary","King room · 2 guests","₹12,800","2 rooms left","https://images.unsplash.com/photo-1611892440504-42a792e24d32?auto=format&fit=crop&w=1200&q=86"],
 ["Forest Pool Villa","Private pool · 2 guests","₹18,500","Last villa","https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=86"],
 ["Aranya Family Suite","2 bedrooms · 4 guests","₹22,400","Available tonight","https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1200&q=86"]];
const services=[["⌂","In-room dining","Kitchen open until 11:30 PM"],["✦","Aahana Spa","Two appointments available today"],["◒","Sunset trail","Guided walk · 5:30 PM"],["◇","Housekeeping","Towels, amenities or room refresh"]];
export default function Home(){
 const [room,setRoom]=useState<number|null>(null),[verified,setVerified]=useState(false),[chat,setChat]=useState(false),[toast,setToast]=useState(""),[msg,setMsg]=useState(""),[sent,setSent]=useState<string[]>([]);
 const notify=(x:string)=>{setToast(x);setTimeout(()=>setToast(""),2400)},send=()=>{if(msg.trim()){setSent([...sent,msg]);setMsg("")}};
 return <main>
  <section className="hero"><div className="shade"/><nav><button className="brand"><b>A</b><span>ARANYA HOUSE<small>Mussoorie</small></span></button><button className="access" onClick={()=>setVerified(true)}><i className={verified?"on":""}/>{verified?"Welcome, Rhea":"Guest access"}</button></nav>
   <div className="heroCopy"><p className="eyebrow">A private retreat above the clouds</p><h1>Your stay,<br/><em>beautifully considered.</em></h1><p>Explore your room, reserve experiences, order dinner—or simply ask Aarohi, your personal concierge.</p><div className="actions"><button className="primary" onClick={()=>document.querySelector("#stays")?.scrollIntoView()}>Explore available rooms →</button><button className="film" onClick={()=>notify("Property film ready to play")}>▶ &nbsp; Watch the property film</button></div></div>
   <div className="strip"><span className="live"/><p><b>3 room types available</b><small>For tonight, 01 August</small></p><p className="weather"><b>19° in Mussoorie</b><small>Mist clearing by sunset</small></p><button onClick={()=>document.querySelector("#stays")?.scrollIntoView()}>View stays ↓</button></div>
  </section>
  <section className="stays" id="stays"><header><div><p className="eyebrow dark">Available tonight</p><h2>Choose the view<br/>you wake up to.</h2></div><p>Every room is shown exactly as it is. Step inside, compare the details, and reserve in a few quiet moments.</p></header>
   <div className="roomGrid">{rooms.map((r,i)=><article key={r[0]}><div className="photo" style={{backgroundImage:`url(${r[4]})`}}><span className={i===1?"badge urgent":"badge"}>{r[3]}</span><button className="play" onClick={()=>notify(`Opening ${r[0]} immersive tour`)}>▶</button><small>60-second room tour</small></div><div className="roomInfo"><span><h3>{r[0]}</h3><p>{r[1]}</p></span><span className="price"><small>Tonight from</small><b>{r[2]}</b></span></div><button className="roomAction" onClick={()=>setRoom(i)}>See room & reserve <span>↗</span></button></article>)}</div>
  </section>
  <section className="hub"><div className="hubCopy"><p className="eyebrow">Your stay, in one place</p><h2>No calls.<br/>No waiting.<br/><em>Just ask.</em></h2><p>Once checked in, every hotel service becomes available here—personalised to your room and stay.</p><button onClick={()=>setVerified(true)}>{verified?"Guest access active ✓":"Preview checked-in experience"}</button></div>
   <div className="phone"><div className="phoneTop">9:41 <span>● ◒</span></div><div className="greet"><small>Good evening</small><h3>{verified?"Rhea, welcome home.":"Welcome to Aranya."}</h3><p>{verified?"Valley Sanctuary · Room 204":"Scan your room card to unlock services"}</p></div><div className="tabs"><b>Your stay</b><span>Dining</span><span>Wellness</span></div><div className="serviceList">{services.map(s=><button key={s[1]} onClick={()=>notify(`${s[1]} request started`)}><i>{s[0]}</i><span><b>{s[1]}</b><small>{s[2]}</small></span><strong>→</strong></button>)}</div><button className="ask" onClick={()=>setChat(true)}><i>✦</i><span><small>ASK AAROHI</small>Your AI concierge</span><b>→</b></button></div>
  </section>
  <section className="closing"><p className="eyebrow">Built around every guest</p><h2>One scan.<br/><em>An unforgettable stay.</em></h2><p>Aranya House is fictional. The experience is not.</p><button className="primary" onClick={()=>notify("Pitch mode ready — branding can be replaced in days")}>See this for your hotel →</button></section>
  <footer><div className="brand"><b>A</b><span>ARANYA HOUSE<small>Mussoorie</small></span></div><p>A demonstration of the next generation of Indian hospitality.</p><small>Private preview · 2026</small></footer><button className="floating" onClick={()=>setChat(true)}><i>✦</i><span>Ask Aarohi<small>Replies instantly</small></span></button>
  {room!==null&&<div className="overlay" onClick={()=>setRoom(null)}><div className="roomModal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setRoom(null)}>×</button><div className="modalPhoto" style={{backgroundImage:`url(${rooms[room][4]})`}}><button onClick={()=>notify("Starting immersive room film")}>▶</button></div><div className="modalText"><p className="eyebrow dark">Available tonight</p><h2>{rooms[room][0]}</h2><p>Wake to cedar forests and soft mountain light. Includes breakfast, evening tea, complimentary minibar and a guided sunrise walk.</p><div className="features"><span>King bed</span><span>42 m²</span><span>Valley view</span><span>Breakfast</span></div><div className="total"><span><small>Tonight</small><b>{rooms[room][2]}</b></span><button className="primary" onClick={()=>notify("Room held for 10 minutes")}>Reserve this room →</button></div></div></div></div>}
  {chat&&<aside className="chat"><header><i>✦</i><span><b>Aarohi</b><small>Aranya concierge · Online</small></span><button onClick={()=>setChat(false)}>×</button></header><div className="messages"><p className="bot">Namaste. I can arrange dinner, a spa ritual, a room upgrade—or anything else during your stay.</p>{sent.map((x,i)=><div key={i}><p className="user">{x}</p><p className="bot">Of course. I found the best available option and can reserve it for you now.</p></div>)}</div><div className="prompts"><button onClick={()=>setMsg("Show me tonight’s dinner menu")}>Dinner menu</button><button onClick={()=>setMsg("Can I upgrade my room?")}>Room upgrade</button></div><div className="input"><input value={msg} onChange={e=>setMsg(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder="Ask anything…"/><button onClick={send}>↑</button></div></aside>}
  {toast&&<div className="toast">✓ &nbsp; {toast}</div>}
 </main>}
