export const FEATURE_REGISTRY = {
  basic_billing: { minimumPlan: "starter", description: "Basic billing and sales" },
  rough_bill: { minimumPlan: "starter", description: "Estimate/rough bills" },
  paid_udhar_bill: { minimumPlan: "starter", description: "Paid + udhar bills" },
  customer_ledger: { minimumPlan: "starter", description: "Customer ledger" },
  record_payment: { minimumPlan: "starter", description: "Record udhar payment" },
  basic_products: { minimumPlan: "starter", description: "Basic product catalog" },
  offline_billing: { minimumPlan: "starter", description: "Local offline billing" },
  seven_day_local_reports: { minimumPlan: "starter", description: "Seven day local reports" },
  cloud_backup: { minimumPlan: "starter", description: "Cloud backup" },
  basic_recycle_bin: { minimumPlan: "starter", description: "Basic recycle bin" },
  auto_two_way_sync: { minimumPlan: "standard", description: "Automatic cloud two-way sync" },
  thirty_day_reports: { minimumPlan: "standard", description: "Thirty day reports" },
  customer_payment_history: { minimumPlan: "standard", description: "Customer payment history" },
  stock_tracking: { minimumPlan: "standard", description: "Stock tracking" },
  low_stock_alerts: { minimumPlan: "standard", description: "Low stock alerts" },
  daily_sales_summary: { minimumPlan: "standard", description: "Daily sales summary" },
  pdf_bill_share: { minimumPlan: "standard", description: "PDF bill sharing" },
  basic_owner_dashboard: { minimumPlan: "standard", description: "Owner dashboard" },
  pin_protected_delete: { minimumPlan: "standard", description: "PIN protected delete" },
  staff_login: { minimumPlan: "growth", description: "Staff login" },
  role_based_access: { minimumPlan: "growth", description: "Role based access" },
  advanced_udhar_reports: { minimumPlan: "growth", description: "Advanced udhar reports" },
  profit_estimate: { minimumPlan: "growth", description: "Profit estimate/report" },
  dynamic_customer_pricing: { minimumPlan: "growth", description: "Dynamic customer pricing" },
  quantity_based_pricing: { minimumPlan: "growth", description: "Quantity based pricing" },
  supplier_entry: { minimumPlan: "starter", description: "Supplier entry" },
  purchase_entry: { minimumPlan: "starter", description: "Purchase entry" },
  stock_adjustment: { minimumPlan: "starter", description: "Stock adjustment" },
  payment_mode_reports: { minimumPlan: "growth", description: "Payment mode reports" },
  monthly_reports: { minimumPlan: "growth", description: "Monthly reports" },
  csv_import_export: { minimumPlan: "growth", description: "CSV import/export" },
  advanced_recycle_bin: { minimumPlan: "growth", description: "Advanced recycle bin" },
  audit_logs: { minimumPlan: "growth", description: "Audit logs" },
  priority_support: { minimumPlan: "growth", description: "Priority support" },
  multi_counter_billing: { minimumPlan: "pro", description: "Multi counter billing" },
  multi_store: { minimumPlan: "pro", description: "Multi store" },
  advanced_inventory: { minimumPlan: "pro", description: "Advanced inventory" },
  batch_expiry: { minimumPlan: "pro", description: "Batch/expiry" },
  gst_reports: { minimumPlan: "pro", description: "GST reports" },
  tally_export: { minimumPlan: "pro", description: "Tally export" },
  whatsapp_reminders: { minimumPlan: "pro", description: "WhatsApp reminders" },
  owner_mobile_dashboard: { minimumPlan: "pro", description: "Owner mobile dashboard" },
  cloud_bill_archive: { minimumPlan: "pro", description: "Cloud bill archive" },
  yearly_reports: { minimumPlan: "pro", description: "Yearly reports" },
  staff_performance_report: { minimumPlan: "pro", description: "Staff performance report" },
  advanced_analytics: { minimumPlan: "pro", description: "Advanced analytics" },
  api_webhook_later: { minimumPlan: "pro", description: "API/webhook later" },
  premium_support: { minimumPlan: "pro", description: "Premium support" },
};

export const OLD_DATA_VIEW_FEATURE = "view_old_data";
