export const FEATURE_REGISTRY = {
  basic_billing: { minimumPlan: "starter", description: "Basic billing and sales" },
  rough_bill: { minimumPlan: "starter", description: "Estimate/rough bills" },
  paid_udhar_bill: { minimumPlan: "starter", description: "Paid + udhar bills" },
  customer_ledger: { minimumPlan: "starter", description: "Customer ledger" },
  record_payment: { minimumPlan: "starter", description: "Record udhar payment" },
  basic_products: { minimumPlan: "starter", description: "Basic product catalog" },
  offline_billing: { minimumPlan: "starter", description: "Local offline billing" },
  seven_day_local_reports: { minimumPlan: "starter", description: "Seven day local reports" },
  cloud_backup: { minimumPlan: "starter", description: "Cloud backup" },
  basic_recycle_bin: { minimumPlan: "starter", description: "Basic recycle bin" },
  auto_two_way_sync: { minimumPlan: "starter", description: "Automatic cloud two-way sync" },
  thirty_day_reports: { minimumPlan: "starter", description: "Thirty day reports" },
  customer_payment_history: { minimumPlan: "starter", description: "Customer payment history" },
  stock_tracking: { minimumPlan: "starter", description: "Stock tracking" },
  low_stock_alerts: { minimumPlan: "starter", description: "Low stock alerts" },
  daily_sales_summary: { minimumPlan: "starter", description: "Daily sales summary" },
  pdf_bill_share: { minimumPlan: "starter", description: "PDF bill sharing" },
  basic_owner_dashboard: { minimumPlan: "starter", description: "Owner dashboard" },
  pin_protected_delete: { minimumPlan: "starter", description: "PIN protected delete" },
  staff_login: { minimumPlan: "growth", description: "Staff login" },
  role_based_access: { minimumPlan: "growth", description: "Role based access" },
  advanced_udhar_reports: { minimumPlan: "growth", description: "Advanced udhar reports" },
  profit_estimate: { minimumPlan: "growth", description: "Profit estimate/report" },
  dynamic_customer_pricing: { minimumPlan: "growth", description: "Dynamic customer pricing" },
  quantity_based_pricing: { minimumPlan: "growth", description: "Quantity based pricing" },
  supplier_entry: { minimumPlan: "starter", description: "Supplier entry" },
  purchase_entry: { minimumPlan: "starter", description: "Purchase entry" },
  stock_adjustment: { minimumPlan: "starter", description: "Stock adjustment" },
  payment_mode_reports: { minimumPlan: "growth", description: "Payment mode reports" },
  monthly_reports: { minimumPlan: "growth", description: "Monthly reports" },
  csv_import_export: { minimumPlan: "growth", description: "CSV import/export" },
  advanced_recycle_bin: { minimumPlan: "growth", description: "Advanced recycle bin" },
  audit_logs: { minimumPlan: "growth", description: "Audit logs" },
  priority_support: { minimumPlan: "growth", description: "Priority support" },
  multi_counter_billing: { minimumPlan: "pro", description: "Multi counter billing" },
  multi_store: { minimumPlan: "pro", description: "Multi store" },
  loyalty_program: { minimumPlan: "pro", description: "Loyalty points and rewards ledger" },
  advanced_inventory: { minimumPlan: "pro", description: "Advanced inventory" },
  batch_expiry: { minimumPlan: "pro", description: "Batch/expiry" },
  gst_reports: { minimumPlan: "pro", description: "GST reports" },
  tally_export: { minimumPlan: "pro", description: "Tally export" },
  whatsapp_reminders: { minimumPlan: "pro", description: "WhatsApp reminders" },
  owner_mobile_dashboard: { minimumPlan: "pro", description: "Owner mobile dashboard" },
  cloud_bill_archive: { minimumPlan: "pro", description: "Cloud bill archive" },
  yearly_reports: { minimumPlan: "pro", description: "Yearly reports" },
  staff_performance_report: { minimumPlan: "pro", description: "Staff performance report" },
  advanced_analytics: { minimumPlan: "pro", description: "Advanced analytics" },
  api_webhook_later: { minimumPlan: "pro", description: "API/webhook later" },
  channel_settlement: { minimumPlan: "pro", description: "Channel order and payout reconciliation" },
  premium_support: { minimumPlan: "pro", description: "Premium support" },
  product_variants: { minimumPlan: "starter", description: "Size, colour and product variants" },
  clothing_rentals: { minimumPlan: "growth", description: "Clothing rental bookings" },
  footwear_size_runs: { minimumPlan: "starter", description: "Footwear size-run stock" },
  vehicle_fitment: { minimumPlan: "starter", description: "Vehicle fitment and alternative parts" },
  serial_imei_tracking: { minimumPlan: "starter", description: "Serial number and IMEI tracking" },
  prescription_tracking: { minimumPlan: "starter", description: "Prescription register" },
  academic_book_lists: { minimumPlan: "starter", description: "School and academic book lists" },
  furniture_order_book: { minimumPlan: "starter", description: "Furniture quotations and order book" },
  tester_stock: { minimumPlan: "starter", description: "Cosmetics tester stock" },
  // The floor: seating, routing tickets to a station, and taking bookings. A
  // takeaway or cloud kitchen opens none of these, which is why they sit on
  // Dine-in and the menu below does not.
  restaurant_tables: { minimumPlan: "growth", description: "Tables, seating and running table bills" },
  restaurant_kot: { minimumPlan: "growth", description: "Kitchen order tickets routed by station" },
  restaurant_table_qr: { minimumPlan: "growth", description: "Per-table guest QR ordering" },
  restaurant_reservations: { minimumPlan: "growth", description: "Table reservations and bookings" },
  restaurant_menu: { minimumPlan: "starter", description: "Restaurant menu management" },
  // Selling a dish has to take its ingredients out of stock on every plan: a
  // cloud kitchen has no floor to buy and no other way to know what it has left.
  restaurant_recipe_inventory: { minimumPlan: "starter", description: "Recipe and ingredient inventory" },
};

export const OLD_DATA_VIEW_FEATURE = "view_old_data";
