import { z } from "zod";
import { PLAN_CODES } from "../subscription/planConfig.js";
import { paiseAmount } from "../../utils/validationSchemas.js";

export const manualPaymentSchema = z.object({
  // shopId is intentionally not accepted here; the authenticated tenant comes from req.shopId.
  planCode: z.enum(PLAN_CODES),
  period: z.enum(["monthly", "yearly"]).default("monthly"),
  amountPaise: paiseAmount({ positive: true }).optional(),
  note: z.string().max(500).optional(),
});

export const retailIntentSchema = z.object({
  amountPaise: paiseAmount({ positive: true }),
  locationId: z.string().min(1).optional(),
  mode: z.enum(["checkout", "dynamic_qr"]).default("checkout"),
});

export const cardTerminalChargeSchema = z.object({
  amountPaise: paiseAmount({ positive: true }),
  locationId: z.string().min(1).optional(),
  // Generated by the cashier client before the request leaves the device. If
  // the HTTP response is lost, retrying this id returns the same local intent
  // and never presents the card a second time.
  requestId: z.string().uuid().optional(),
});

export const reconcileCardTerminalChargeSchema = z.object({
  outcome: z.enum(["charged", "not_charged"]),
  providerPaymentId: z.string().trim().min(3).max(100).optional(),
  reason: z.string().trim().min(3).max(500),
  ownerPin: z.string().regex(/^\d{4}$/).optional(),
}).superRefine((value, ctx) => {
  if (value.outcome === "charged" && !value.providerPaymentId) {
    ctx.addIssue({ code: z.ZodIssueCode.custom, path: ["providerPaymentId"], message: "Provider payment reference is required when the card was charged" });
  }
});

export const verifyRetailIntentSchema = z.object({
  razorpay_order_id: z.string().min(1),
  razorpay_payment_id: z.string().min(1),
  razorpay_signature: z.string().min(1),
});
