ALTER TABLE "Customer" ADD COLUMN "udharLimit" DOUBLE PRECISION;
ALTER TABLE "Customer" ADD COLUMN "dueDate" TEXT;
ALTER TABLE "Customer" ADD COLUMN "promiseToPayDate" TEXT;
ALTER TABLE "Customer" ADD COLUMN "notes" TEXT;
