-- @replay-safe
-- Existing accounting records belong to the INR ledger. No money is converted.
ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "countryCode" TEXT NOT NULL DEFAULT 'IN';
ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "currencyCode" TEXT NOT NULL DEFAULT 'INR';
ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "accountingTimeZone" TEXT NOT NULL DEFAULT 'Asia/Kolkata';
ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "taxRegime" TEXT NOT NULL DEFAULT 'GST';
ALTER TABLE "UdharLedger" ADD COLUMN IF NOT EXISTS "countryCode" TEXT NOT NULL DEFAULT 'IN';
ALTER TABLE "UdharLedger" ADD COLUMN IF NOT EXISTS "currencyCode" TEXT NOT NULL DEFAULT 'INR';
ALTER TABLE "UdharLedger" ADD COLUMN IF NOT EXISTS "accountingTimeZone" TEXT NOT NULL DEFAULT 'Asia/Kolkata';
ALTER TABLE "UdharLedger" ADD COLUMN IF NOT EXISTS "taxRegime" TEXT NOT NULL DEFAULT 'GST';
ALTER TABLE "FinancialLedger" ADD COLUMN IF NOT EXISTS "countryCode" TEXT NOT NULL DEFAULT 'IN';
ALTER TABLE "FinancialLedger" ADD COLUMN IF NOT EXISTS "currencyCode" TEXT NOT NULL DEFAULT 'INR';
ALTER TABLE "FinancialLedger" ADD COLUMN IF NOT EXISTS "accountingTimeZone" TEXT NOT NULL DEFAULT 'Asia/Kolkata';
ALTER TABLE "FinancialLedger" ADD COLUMN IF NOT EXISTS "taxRegime" TEXT NOT NULL DEFAULT 'GST';
ALTER TABLE "JournalEntry" ADD COLUMN IF NOT EXISTS "countryCode" TEXT NOT NULL DEFAULT 'IN';
ALTER TABLE "JournalEntry" ADD COLUMN IF NOT EXISTS "currencyCode" TEXT NOT NULL DEFAULT 'INR';
ALTER TABLE "JournalEntry" ADD COLUMN IF NOT EXISTS "accountingTimeZone" TEXT NOT NULL DEFAULT 'Asia/Kolkata';
ALTER TABLE "JournalEntry" ADD COLUMN IF NOT EXISTS "taxRegime" TEXT NOT NULL DEFAULT 'GST';
